version: "3"
services:
       node-web-api:
           container_name: node-api
           image: node_mongo_web_app
           restart: always
           build: .
           ports:
             - "3001:3001"
           depends_on:
             - mongo
       mongo:
            container_name: mongodb
            image: mongo:3.6.3
            ports:
              - "27017:27017"